version: "2.4"
services:
  accounts:
    image: nicolasduminil/account:1.0-SNAPSHOT
    hostname: accounts
    container_name: accounts
    #ports:
    #  - "8081:8081"
    network_mode: host
  transfers:
    image: nicolasduminil/transfer:1.0-SNAPSHOT
    hostname: transfers
    container_name: transfers
    depends_on:
      - accounts
    #ports:
    #  - "8080:8080"
    network_mode: host
